import React, { useState } from "react";
import "antd/dist/antd.css";
import { Breadcrumb, Dropdown, Layout, Menu, Spin } from "antd";
import Link from "next/link";
import { useRouter } from "next/router";
import Head from "next/head";
import "../styles/Home.module.css";
import {
  LogoutOutlined,
  OrderedListOutlined,
  TeamOutlined,
  UserOutlined,
} from "@ant-design/icons";
import Avatar from "antd/lib/avatar/avatar";
const { Header, Sider, Content, Footer } = Layout;
const LayoutPage = ({ children }) => {
  const [collapsed, setCollapsed] = useState(false);
  const [loading, setLoading] = useState(false);
  const router = useRouter();
  const currentPath = router.route;

  const onCollapse = (collapsed) => {
    setCollapsed(collapsed);
  };

  const key = ["/", "/users", "/sellers", "/login"];
  let selectedKeys = [];

  for (let i = key.length - 1; i >= 0; i--) {
    if (currentPath.includes(key[i])) {
      selectedKeys = [key[i]];
      break;
    }
  }

  const onClick = ({ key }) => {
    setLoading(true);
    setTimeout(() => {
      router.push(key);
    }, 1500);
  };

  const dropdown = (
    <Menu onClick={onClick} loading={loading}>
      <Menu.Item key={key[3]}>
        <LogoutOutlined /> Logout
      </Menu.Item>
    </Menu>
  );

  return (
    <Layout style={{ minHeight: "100vh" }}>
      <Head>
        <title>Dashboard Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sider collapsible collapsed={collapsed} onCollapse={onCollapse}>
        <div className="logo" />
        <Menu
          theme="dark"
          mode="inline"
          // defaultSelectedKeys={key[0]}
          selectedKeys={selectedKeys}
          style={{ margin: "150px 0" }}
          onClick={({ key }) => {
            router.push(key);
          }}
        >
          <Menu.Item key={key[0]} icon={<OrderedListOutlined />}>
            <Link href="/">
              <a> Categories</a>
            </Link>
          </Menu.Item>
          <Menu.Item key={key[1]} icon={<TeamOutlined />}>
            <Link href="/users">
              <a> Users</a>
            </Link>
          </Menu.Item>
          <Menu.Item key={key[2]} icon={<UserOutlined />}>
            <Link href="/sellers">
              <a> Sellers</a>
            </Link>
          </Menu.Item>
        </Menu>
      </Sider>
      <Layout className="site-layout">
        <Header
          style={{
            padding: "0 20px",
            background: "rgba(255, 255, 255, 0.3)",
            display: "flex",
            justifyContent: "space-between",
          }}
        >
          <div>
            <h2>Welcome to Admin Page</h2>
          </div>
          <div style={{ float: "right" }}>
            <Dropdown overlay={dropdown}>
              <Avatar
                size="large"
                icon={<UserOutlined />}
                onClick={(e) => e.preventDefault()}
              />
            </Dropdown>
          </div>
        </Header>
        <Content
          className="site-layout-background"
          style={{
            // margin: "24px 16px",
            margin: 20,
            minHeight: 280,
          }}
        >
          <Breadcrumb style={{ margin: "16px 0" }}></Breadcrumb>
          <div
            className="site-layout-background"
            style={{ padding: 24, minHeight: 360, background: "#fff" }}
          >
            {children}
          </div>
        </Content>
        <Footer style={{ textAlign: "center" }}>©2021 Created by Nhóm 8</Footer>
      </Layout>
    </Layout>
  );
};
export default LayoutPage;
