import React from "react";
import Head from "next/head";
import { Card, Layout } from "antd";
const { Content } = Layout;
const LoginLayout = ({ children }) => {
  return (
    <Layout
      className="layout"
      style={{
        height: "100vh",
        backgroundSize: "cover",
        backgroundImage:
          "url(" +
          "https://phunugioi.com/wp-content/uploads/2020/02/mau-background-dep.jpg" +
          ")",
      }}
    >
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          height: "100%",
        }}
      >
        <Card
          style={{
            alignItems: "center",
            flexDirection: "row",
            justifyContent: "center",
            alignItems: "center",
            alignContent: "center",
            backgroundColor: "white",
            width: "50%",
            borderRadius: "20px",
          }}
        >
          <div
            style={{
              display: "flex",
              justifyContent: "center",
              padding: "30px 0",
            }}
          >
            <h1>Welcome To Admin Page!</h1>
          </div>
          <div style={{ display: "flex", justifyContent: "center" }}>
            <Content
              style={{
                padding: "0 20px",
                minHeight: "100%",
                maxWidth: "50%",
              }}
            >
              <div className="site-layout-content">{children}</div>
            </Content>
          </div>
        </Card>
      </div>
    </Layout>
  );
};

export default LoginLayout;
